// AUTO-GENERATED by palette/build.js — DO NOT EDIT.
// Regenerado automáticamente al cambiar palette/master.css.
// Source: /home/lmz/nordicos/palette/master.css
// See /home/lmz/nordicos/palette/README.md for details.

export const theme = {
  bg: '#0b0f14',
  surface: '#151c24',
  'surface-alt': '#1a2332',
  border: '#3b556d',
  accent: '#78c7ff',
  'accent-soft': '#a0d4ff',
  text: '#d4dde3',
  'text-muted': '#8a9bab',
  success: '#6fbf73',
  warning: '#d89b3c',
  error: '#b84c4c',
  shadow: '#1a1a1a',
} as const
